fix(ui): remove int

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -17,7 +17,6 @@ defaults:
     working-directory: ./frontend
 
 jobs:
-
   code-analysis:
     runs-on: ubuntu-latest
     steps:
@@ -33,8 +32,8 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: ${{ env.NODE_VERSION }}
-          cache: 'yarn'
-          cache-dependency-path: 'frontend/yarn.lock'
+          cache: "yarn"
+          cache-dependency-path: "frontend/yarn.lock"
 
       - name: Prettier
         id: prettier
@@ -48,10 +47,10 @@ jobs:
         if: ${{ success() || failure() }}
         run: yarn run lint:ci
 
-      - name: i18n sync
-        id: i18n
-        if: ${{ success() || failure() }}
-        run: make i18n-ci
+      # - name: i18n sync
+      #   id: i18n
+      #   if: ${{ success() || failure() }}
+      #   run: make i18n-ci
 
       - name: Unit Tests
         id: unit
@@ -67,8 +66,7 @@ jobs:
           echo '| Prettier | ${{ steps.prettier.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
           echo '| ESLint | ${{ steps.eslint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
           echo '| i18n | ${{ steps.i18n.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
-          echo '| Unit Tests | ${{ steps.unit.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY 
-
+          echo '| Unit Tests | ${{ steps.unit.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
 
   release:
     runs-on: ubuntu-latest
@@ -79,7 +77,6 @@ jobs:
       packages: write
 
     steps:
-
       - name: Checkout
         uses: actions/checkout@v4
 
@@ -91,8 +88,7 @@ jobs:
             ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}
           labels: |
             org.label-schema.docker.cmd=docker run -d -p 3000:3000 ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}:latest
-          flavor:
-            latest=false
+          flavor: latest=false
           tags: |
             type=ref,event=branch
             type=sha
